# Generated by Django 5.0 on 2023-12-27 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_customers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='testimonials/')),
                ('icon', models.FileField(upload_to='testimonials/')),
                ('icon_bg', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('testimonial_description', models.TextField()),
                ('testimonial_author', models.CharField(max_length=255)),
                ('author_designation', models.CharField(max_length=255)),
                ('testimonial_logo', models.FileField(upload_to='testimonials/')),
            ],
        ),
        migrations.AlterField(
            model_name='customers',
            name='image',
            field=models.FileField(upload_to='promoters/'),
        ),
    ]
