# Generated by Django 5.0 on 2023-12-28 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_features_alter_customers_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='videoBlog/')),
                ('title', models.CharField(max_length=255)),
                ('logo', models.FileField(upload_to='videoBlog/')),
            ],
        ),
    ]
