# Generated by Django 5.0 on 2023-12-28 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_testimonial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(upload_to='Testimonials1/'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='Testimonials1/'),
        ),
    ]
