# Generated by Django 5.0 on 2023-12-28 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_product_alter_marketingfeatures_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bg_color',
            field=models.CharField(default=123, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='btn_color',
            field=models.CharField(default=333, max_length=255),
            preserve_default=False,
        ),
    ]
