# Generated by Django 5.0 on 2024-01-05 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='white_logo',
            field=models.FileField(blank=True, null=True, upload_to='promoters/'),
        ),
    ]
