# Generated by Django 5.0 on 2024-01-08 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_customers_white_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hero_image',
            field=models.FileField(default='a', upload_to='products/hero_images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(default='Studio', max_length=255),
            preserve_default=False,
        ),
    ]
