# Generated by Django 5.0 on 2024-01-08 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_product_hero_image_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_bg_color',
            field=models.CharField(default='#ffc9b7', max_length=255),
            preserve_default=False,
        ),
    ]
